---
- name: Copy the configuration file
  command: cp /usr/share/instack-undercloud/undercloud.conf.sample /home/stack/undercloud.conf

- name: Disable tempest
  command: sed -i s/#enable_tempest.*/enable_tempest\ =\ false/ undercloud.conf

- name: Install undercloud
  environment:
  shell: openstack undercloud install 

- name: Build images
  environment:
    USE_DELOREAN_TRUNK: 1
    DELOREAN_TRUNK_REPO: "http://trunk.rdoproject.org/liberty/centos7/current-passed-ci/"
    DELOREAN_REPO_FILE: "/etc/yum.repos.d/delorean.repo"
  shell: openstack overcloud image build --all

- name: Upload images
  shell: source /home/stack/stackrc; openstack overcloud image upload
  args:
    chdir: /home/stack
