---
- name: Copy the configuration file
  command: cp /usr/share/instack-undercloud/undercloud.conf.sample /home/stack/undercloud.conf

- name: Disable tempest
  command: sed -i s/#enable_tempest.*/enable_tempest\ =\ false/ undercloud.conf

- name: Install undercloud
  shell: openstack undercloud install 

- name: Build images
  environment:
    DELOREAN_TRUNK_MGT_REPO: "http://trunk.rdoproject.org/centos7/current/"
    DIB_YUM_REPO_CONF: "/etc/yum.repos.d/delorean.repo /etc/yum.repos.d/delorean-deps.repo"
  shell: openstack overcloud image build --all

- name: Upload images
  shell: source /home/stack/stackrc; openstack overcloud image upload
