---
- name: Copy the configuration file
  command: cp /usr/share/instack-undercloud/undercloud.conf.sample /home/stack/undercloud.conf

- name: Install undercloud
  environment:
  shell: openstack undercloud install 

- name: Build images
  environment:
    USE_DELOREAN_TRUNK: 1
    DELOREAN_TRUNK_REPO: "http://trunk.rdoproject.org/centos7-liberty/current/"
    DELOREAN_REPO_FILE: "delorean.repo"
  shell: openstack overcloud image build --all

- name: Upload images
  shell: source /home/stack/stackrc; openstack overcloud image upload
  args:
    chdir: /home/stack
