---
- name: Copy the configuration file
  command: cp /usr/share/instack-undercloud/undercloud.conf.sample /home/stack/undercloud.conf

- name: Disable tempest
  command: sed -i s/#enable_tempest.*/enable_tempest\ =\ false/ undercloud.conf

- name: Install undercloud
  shell: openstack undercloud install 
