---
- name: Enable EPEL
  yum: name=epel-release state=installed 

- name: Enable last known good RDO Trunk Delorean repository
  shell: curl -o /etc/yum.repos.d/delorean.repo http://trunk.rdoproject.org/centos7/current-tripleo/delorean.repo

- name: Enable the Delorean Deps repository
  shell: sudo curl -o /etc/yum.repos.d/delorean-deps.repo http://trunk.rdoproject.org/centos7/delorean-deps.repo
