---
- name: Enable RDO Kilo
  command: yum install -y https://rdo.fedorapeople.org/openstack-kilo/rdo-release-kilo.rpm
  ignore_errors: yes

- name: Enable RDO Trunk
  shell: curl -o /etc/yum.repos.d/delorean.repo http://trunk.rdoproject.org/centos7/df/03/df0377d64e1ef0b53c4e78a8ff6a50159de5131a_733f1417/delorean.repo

